namespace DailyAccount.App.Localization;

/// <summary>
/// Every UI string in both languages, side by side (docs/adr/0006-localization-dictionary.md).
/// {0}, {1} are string.Format placeholders.
/// </summary>
internal static class Strings
{
    public static readonly Dictionary<string, (string En, string Bn)> All = new()
    {
        // ----- Tabs & common -----
        ["Tab_Home"] = ("Home", "হোম"),
        ["Tab_Dues"] = ("Dues", "দেনা"),
        ["Tab_Accounts"] = ("Accounts", "অ্যাকাউন্ট"),
        ["Tab_Liabilities"] = ("Liabilities", "দায়"),
        ["Tab_Reports"] = ("Reports", "রিপোর্ট"),
        ["AppName"] = ("Daily Account", "দৈনিক হিসাব"),
        ["Save"] = ("Save", "সেভ করুন"),
        ["Cancel"] = ("Cancel", "বাতিল"),
        ["Delete"] = ("Delete", "মুছুন"),
        ["OK"] = ("OK", "ঠিক আছে"),
        ["Yes"] = ("Yes", "হ্যাঁ"),
        ["No"] = ("No", "না"),
        ["Amount"] = ("Amount", "পরিমাণ"),
        ["Date"] = ("Date", "তারিখ"),
        ["Note"] = ("Note (optional)", "নোট (ঐচ্ছিক)"),
        ["Category"] = ("Category", "ক্যাটাগরি"),
        ["Name"] = ("Name", "নাম"),
        ["Optional"] = ("Optional", "ঐচ্ছিক"),
        ["None"] = ("None", "কোনোটি নয়"),
        ["Pay"] = ("Pay", "পরিশোধ"),
        ["Repay"] = ("Repay", "ফেরত দিন"),
        ["SeeAll"] = ("See all", "সব দেখুন"),
        ["Confirm_Delete"] = ("Delete this record?", "এই রেকর্ডটি মুছে ফেলবেন?"),
        ["Last"] = ("Last", "শেষ"),
        ["Status_Pending"] = ("Pending", "বাকি"),
        ["Status_Partial"] = ("Partial", "আংশিক"),
        ["Status_Paid"] = ("Paid", "পরিশোধিত"),
        ["Status_Upcoming"] = ("Upcoming", "আসন্ন"),
        ["DueOn"] = ("Due {0}", "শেষ তারিখ {0}"),
        ["Income"] = ("Income", "আয়"),
        ["Dues"] = ("Dues", "দেনা"),
        ["Expenses"] = ("Expenses", "খরচ"),
        ["Total"] = ("Total", "মোট"),
        ["Paid"] = ("Paid", "পরিশোধিত"),
        ["Remaining"] = ("Remaining", "বাকি"),

        // ----- Dashboard -----
        ["Dash_ProjectedSavings"] = ("Projected savings this month", "এ মাসের সম্ভাব্য সঞ্চয়"),
        ["Dash_Formula"] = ("Income {0} − dues {1} − expenses {2}", "আয় {0} − দেনা {1} − খরচ {2}"),
        ["Dash_DuesSub"] = ("{0} paid · {1} pending", "{0} পরিশোধ · {1}টি বাকি"),
        ["Dash_CardSub"] = ("+ {0} on card", "+ কার্ডে {0}"),
        ["Dash_SavedSoFar"] = ("Saved so far", "এখন পর্যন্ত সঞ্চয়"),
        ["Dash_BeforeDues"] = ("before paying dues", "দেনা পরিশোধের আগে"),
        ["Dash_DueThisMonth"] = ("Due this month", "এ মাসের দেনা"),
        ["Dash_NoDues"] = ("Nothing to pay this month.", "এ মাসে কিছু পরিশোধ করার নেই।"),
        ["Dash_WhereYouStand"] = ("Where you stand", "আপনার অবস্থান"),
        ["Dash_Welcome"] = ("Welcome! Start by adding your bank, cash and bKash accounts.", "স্বাগতম! প্রথমে আপনার ব্যাংক, ক্যাশ ও বিকাশ অ্যাকাউন্ট যোগ করুন।"),
        ["InAllAccounts"] = ("In all accounts", "সব অ্যাকাউন্টে"),
        ["YouOwe"] = ("You owe", "আপনার দেনা"),
        ["OthersOweYou"] = ("Others owe you", "অন্যের কাছে পাওনা"),
        ["NetWorth"] = ("Net worth", "নিট সম্পদ"),
        ["Fc_Title"] = ("{0} forecast", "{0} পূর্বাভাস"),
        ["Fc_StillToPay"] = ("Still to pay this month", "এ মাসে এখনও বাকি"),
        ["Fc_NextDues"] = ("Next month dues", "আগামী মাসের দেনা"),
        ["Fc_Unbilled"] = ("Card purchases not yet billed", "কার্ডের বিল এখনও আসেনি"),
        ["Fc_Spending"] = ("Expected spending (3-month avg)", "সম্ভাব্য খরচ (৩ মাসের গড়)"),
        ["Fc_Needed"] = ("Needed", "প্রয়োজন"),
        ["Fc_Available"] = ("Balance + expected income", "ব্যালেন্স + সম্ভাব্য আয়"),
        ["Fc_NoBorrow"] = ("No need to borrow. End balance ≈ {0}", "ধার লাগবে না। মাস শেষে ব্যালেন্স ≈ {0}"),
        ["Fc_Borrow"] = ("You may need to borrow {0}", "আপনার {0} ধার লাগতে পারে"),
        ["Fc_SetIncome"] = ("Set your expected monthly income in Settings for a better forecast.", "ভালো পূর্বাভাসের জন্য সেটিংসে মাসিক আয় দিন।"),

        // ----- Add transaction -----
        ["AddTx_Title"] = ("Add transaction", "লেনদেন যোগ করুন"),
        ["AddTx_EditTitle"] = ("Edit entry", "এন্ট্রি এডিট"),
        ["Entries_Title"] = ("All entries", "সব এন্ট্রি"),
        ["Entries_Open"] = ("All entries of this month ›", "এ মাসের সব এন্ট্রি ›"),
        ["Entries_Summary"] = ("{0} entries · in {1} · out {2}", "{0}টি এন্ট্রি · এসেছে {1} · গেছে {2}"),
        ["Entries_TapHint"] = ("Tap an entry to edit it.", "এডিট করতে এন্ট্রিতে চাপুন।"),
        ["Entries_Empty"] = ("No entries this month.", "এ মাসে কোনো এন্ট্রি নেই।"),
        ["Err_EditNotAllowed"] = ("This entry can't be edited (a bill payment or borrow/lend). Delete it and enter it again.", "এই এন্ট্রি এডিট করা যাবে না (বিল পরিশোধ বা ধার)। মুছে আবার লিখুন।"),
        ["AddTx_Button"] = ("+ Add income / expense", "+ আয় / খরচ যোগ করুন"),
        ["Type_Income"] = ("Income", "আয়"),
        ["Type_Expense"] = ("Expense", "খরচ"),
        ["Type_Card"] = ("Card purchase", "কার্ডে কেনা"),
        ["Type_Transfer"] = ("Transfer", "ট্রান্সফার"),
        ["Type_Borrow"] = ("Borrow", "ধার নিলাম"),
        ["Type_Lend"] = ("Lend", "ধার দিলাম"),
        ["Hint_Income"] = ("Adds money to the account. Counts as this month's income.", "অ্যাকাউন্টে টাকা যোগ হবে। এ মাসের আয় হিসেবে গণ্য হবে।"),
        ["Hint_Expense"] = ("Takes money from the account now. Counts as this month's expense.", "এখনই অ্যাকাউন্ট থেকে টাকা কমবে। এ মাসের খরচ হিসেবে গণ্য হবে।"),
        ["Hint_Card"] = ("No bank balance changes now. It goes on the next card statement and becomes a due.", "এখন ব্যাংক ব্যালেন্স বদলাবে না। পরের স্টেটমেন্টে যোগ হয়ে দেনা হবে।"),
        ["Hint_Transfer"] = ("Moves money between your own accounts. Not income, not expense.", "নিজের অ্যাকাউন্টগুলোর মধ্যে টাকা সরানো। আয়ও না, খরচও না।"),
        ["Hint_Borrow"] = ("Money comes into your account and a due is created until you repay.", "টাকা অ্যাকাউন্টে আসবে এবং ফেরত না দেওয়া পর্যন্ত দেনা থাকবে।"),
        ["Hint_Lend"] = ("Money leaves your account and is tracked under \"Others owe you\".", "টাকা অ্যাকাউন্ট থেকে যাবে এবং \"অন্যের কাছে পাওনা\"-তে দেখাবে।"),
        ["Account"] = ("Account", "অ্যাকাউন্ট"),
        ["FromAccount"] = ("From account", "যে অ্যাকাউন্ট থেকে"),
        ["ToAccount"] = ("To account", "যে অ্যাকাউন্টে"),
        ["ReceivedIn"] = ("Received in (optional)", "যে অ্যাকাউন্টে এল (ঐচ্ছিক)"),
        ["Card"] = ("Card", "কার্ড"),
        ["PersonName"] = ("Person's name", "ব্যক্তির নাম"),
        ["ReturnDate"] = ("Return by", "ফেরতের তারিখ"),
        ["NeedAccountFirst"] = ("Add an account first.", "আগে একটি অ্যাকাউন্ট যোগ করুন।"),
        ["NeedCardFirst"] = ("Add a credit card first (Liabilities → Cards).", "আগে একটি ক্রেডিট কার্ড যোগ করুন (দায় → কার্ড)।"),

        // ----- Dues -----
        ["Dues_Title"] = ("Dues", "দেনা"),
        ["Dues_Overdue"] = ("Overdue from earlier months: {0}", "আগের মাসের বকেয়া: {0}"),
        ["Dues_Pending"] = ("To pay", "পরিশোধ বাকি"),
        ["Dues_NoDate"] = ("No fixed date", "নির্দিষ্ট তারিখ নেই"),
        ["Dues_PaidSection"] = ("Paid this month", "এ মাসে পরিশোধিত"),
        ["Dues_DueTotal"] = ("Due this month", "এ মাসে বাকি"),
        ["Dues_BudgetLine"] = ("Budget {0} · spent {1}", "বাজেট {0} · খরচ {1}"),
        ["Dues_NotPaid"] = ("Not paid yet", "এখনও বাকি"),
        ["Dues_ItemSub"] = ("Estimate {0} · spent {1}", "আনুমানিক {0} · খরচ {1}"),
        ["Dues_Over"] = ("over by {0}", "{0} বেশি খরচ"),
        ["Dues_AddExpense"] = ("+ Expense", "+ খরচ"),
        ["Dues_FullyPaid"] = ("Fully paid", "সম্পূর্ণ পরিশোধিত"),
        ["Dues_CardLoans"] = ("Card & loan payments", "কার্ড ও লোন পরিশোধ"),
        ["Dues_CardLoansHint"] = ("Paid separately; not part of the Due above (like your sheet).", "আলাদাভাবে পরিশোধ হয়; উপরের বাকিতে ধরা হয়নি (শিটের মতো)।"),
        ["Dues_NextMonth"] = ("Coming next month", "আগামী মাসে আসছে"),
        ["Dues_Nothing"] = ("Nothing here.", "কিছু নেই।"),
        ["Due_CardBill"] = ("{0} bill ({1})", "{0} বিল ({1})"),
        ["Due_Borrowed"] = ("{0} (borrowed)", "{0} (ধার)"),

        // ----- Pay -----
        ["Pay_Title"] = ("Pay {0}", "পরিশোধ: {0}"),
        ["Pay_DueAmount"] = ("Due amount", "দেনার পরিমাণ"),
        ["Pay_AlreadyPaid"] = ("Already paid", "আগে পরিশোধিত"),
        ["Pay_AmountToPay"] = ("Amount to pay", "পরিশোধের পরিমাণ"),
        ["Pay_PartialHint"] = ("Pay less to make a partial payment. The rest stays as a due.", "কম দিলে আংশিক পরিশোধ হবে। বাকিটা দেনা থাকবে।"),
        ["Pay_From"] = ("Pay from", "যে অ্যাকাউন্ট থেকে"),
        ["Return_Title"] = ("Money returned by {0}", "{0} টাকা ফেরত দিল"),
        ["Return_Owed"] = ("Still owes you", "এখনও পাওনা"),
        ["Return_Into"] = ("Received into", "যে অ্যাকাউন্টে এল"),
        ["Return_Button"] = ("Save return", "ফেরত সেভ করুন"),

        // ----- Accounts -----
        ["Accounts_Title"] = ("Accounts", "অ্যাকাউন্ট"),
        ["TotalSavings"] = ("Total savings (all accounts)", "মোট সঞ্চয় (সব অ্যাকাউন্ট)"),
        ["AddAccount"] = ("+ Add account", "+ অ্যাকাউন্ট যোগ"),
        ["AddAccount_Title"] = ("New account", "নতুন অ্যাকাউন্ট"),
        ["AccountName_Hint"] = ("e.g. DBBL, Cash, bKash", "যেমন: DBBL, ক্যাশ, বিকাশ"),
        ["AccountType"] = ("Type", "ধরন"),
        ["AccountType_Bank"] = ("Bank", "ব্যাংক"),
        ["AccountType_Cash"] = ("Cash", "ক্যাশ"),
        ["AccountType_MobileWallet"] = ("Mobile wallet", "মোবাইল ওয়ালেট"),
        ["OpeningBalance"] = ("Current balance (today)", "বর্তমান ব্যালেন্স (আজ)"),
        ["History"] = ("History", "লেনদেনের ইতিহাস"),
        ["NoTransactions"] = ("No transactions yet.", "এখনও কোনো লেনদেন নেই।"),
        ["Opening"] = ("Opening balance", "শুরুর ব্যালেন্স"),

        // ----- Transaction types (history rows) -----
        ["Tx_Income"] = ("Income", "আয়"),
        ["Tx_Expense"] = ("Expense", "খরচ"),
        ["Tx_Transfer"] = ("Transfer", "ট্রান্সফার"),
        ["Tx_CardPurchase"] = ("Card purchase", "কার্ডে কেনা"),
        ["Tx_DuePayment"] = ("Payment", "পরিশোধ"),
        ["Tx_BorrowIn"] = ("Borrowed", "ধার নেওয়া"),
        ["Tx_LendOut"] = ("Lent", "ধার দেওয়া"),
        ["Tx_LendReturn"] = ("Returned to you", "ফেরত পাওয়া"),
        ["TransferTo"] = ("To {0}", "{0}-এ"),
        ["TransferFrom"] = ("From {0}", "{0} থেকে"),

        // ----- Liabilities -----
        ["Liab_Title"] = ("Liabilities", "দায়"),
        ["Liab_TotalOwe"] = ("You owe in total", "মোট দেনা"),
        ["Loans"] = ("Loans", "লোন"),
        ["Cards"] = ("Cards", "কার্ড"),
        ["Bills"] = ("Bills", "বিল"),
        ["Personal"] = ("Personal", "ব্যক্তিগত"),
        ["BillsPersonal"] = ("Bills & personal", "বিল ও ব্যক্তিগত"),
        ["AddLoan"] = ("+ Add loan", "+ লোন যোগ"),
        ["AddLoan_Title"] = ("New loan", "নতুন লোন"),
        ["Lender"] = ("Lender (bank / person)", "ঋণদাতা (ব্যাংক / ব্যক্তি)"),
        ["TotalPayable"] = ("Total to repay (with interest)", "মোট পরিশোধযোগ্য (সুদসহ)"),
        ["Installments"] = ("Number of monthly installments", "মাসিক কিস্তির সংখ্যা"),
        ["FirstInstallment"] = ("First installment date", "প্রথম কিস্তির তারিখ"),
        ["PayFrom"] = ("Usually paid from", "সাধারণত যে অ্যাকাউন্ট থেকে"),
        ["Loan_Preview"] = ("{0} × {1}, last {2}", "{0} × {1}, শেষ কিস্তি {2}"),
        ["Loan_Sub"] = ("{0} · {1} installments", "{0} · {1}টি কিস্তি"),
        ["Loan_Progress"] = ("{0} of {1} paid", "{1}টির মধ্যে {0}টি পরিশোধিত"),
        ["Loan_Next"] = ("Next: {0} on {1}", "পরবর্তী: {1} তারিখে {0}"),
        ["Loan_Done"] = ("Fully paid", "সম্পূর্ণ পরিশোধিত"),
        ["AddCard"] = ("+ Add card", "+ কার্ড যোগ"),
        ["AddCard_Title"] = ("New credit card", "নতুন ক্রেডিট কার্ড"),
        ["CardName"] = ("Card name", "কার্ডের নাম"),
        ["CreditLimit"] = ("Credit limit", "ক্রেডিট লিমিট"),
        ["StatementDay"] = ("Statement day (1–28)", "স্টেটমেন্টের দিন (১–২৮)"),
        ["DueDay"] = ("Payment due day", "পরিশোধের শেষ দিন"),
        ["Card_Sub"] = ("Statement on day {0} · pay by day {1}", "{0} তারিখে স্টেটমেন্ট · {1} তারিখের মধ্যে পরিশোধ"),
        ["Card_Used"] = ("Used {0}", "ব্যবহৃত {0}"),
        ["Card_Available"] = ("Available {0}", "বাকি লিমিট {0}"),
        ["Card_Billed"] = ("Billed, unpaid", "বিল এসেছে, বাকি"),
        ["Card_CurrentCycle"] = ("Current cycle since {0}", "{0} থেকে চলতি সাইকেল"),
        ["Card_NextStatement"] = ("Becomes a due on {0}", "{0} তারিখে দেনা হবে"),
        ["AddBill"] = ("+ Add bill", "+ বিল যোগ"),
        ["AddBill_Title"] = ("New monthly bill", "নতুন মাসিক বিল"),
        ["BillName"] = ("Bill name (rent, DPS, internet…)", "বিলের নাম (ভাড়া, ডিপিএস, ইন্টারনেট…)"),
        ["BillDay"] = ("Due day of month", "মাসের কোন দিন"),
        ["BillStart"] = ("First month", "প্রথম মাস"),
        ["Bill_Sub"] = ("Every month on day {0}", "প্রতি মাসের {0} তারিখ"),
        ["Bill_Stopped"] = ("Stopped", "বন্ধ"),
        ["StopBill"] = ("Stop", "বন্ধ করুন"),
        ["Confirm_StopBill"] = ("Stop this bill from next month?", "আগামী মাস থেকে এই বিল বন্ধ করবেন?"),
        ["Borrowed_Section"] = ("You borrowed", "আপনি ধার নিয়েছেন"),
        ["Lent_Section"] = ("You lent", "আপনি ধার দিয়েছেন"),
        ["Borrow"] = ("+ Borrow", "+ ধার নিলাম"),
        ["Lend"] = ("+ Lend", "+ ধার দিলাম"),
        ["MoneyReturned"] = ("Money returned", "টাকা ফেরত পেলাম"),
        ["Debt_BorrowedSub"] = ("Borrowed {0} on {1}", "{1} তারিখে {0} ধার"),
        ["Debt_LentSub"] = ("Lent {0} on {1}", "{1} তারিখে {0} ধার দেওয়া"),
        ["Debt_Settled"] = ("Settled", "পরিশোধিত"),

        // ----- Reports -----
        ["Reports_Title"] = ("Report", "রিপোর্ট"),
        ["CashFlow"] = ("Cash flow", "নগদ প্রবাহ"),
        ["CashFlowSub"] = ("Real money in and out of your accounts", "অ্যাকাউন্টে আসা ও যাওয়া আসল টাকা"),
        ["DuesPaid"] = ("Loan & Credit Card Paid", "লোন ও ক্রেডিট কার্ড পরিশোধ"),
        ["CashExpenses"] = ("Cash expenses", "নগদ খরচ"),
        ["DuesStill"] = ("Dues still to pay", "বাকি দেনা"),
        ["ProjectedSavings"] = ("Projected savings", "সম্ভাব্য সঞ্চয়"),
        ["SpendingByCategory"] = ("Spending by category", "ক্যাটাগরি অনুযায়ী খরচ"),
        ["SpendingSub"] = ("Cash {0} + card {1}", "নগদ {0} + কার্ড {1}"),
        ["Last6Months"] = ("Savings, last 6 months", "গত ৬ মাসের সঞ্চয়"),
        ["Uncategorized"] = ("Uncategorized", "ক্যাটাগরি নেই"),
        ["NoSpending"] = ("No spending this month.", "এ মাসে কোনো খরচ নেই।"),

        // ----- Settings -----
        ["Settings_Title"] = ("Settings", "সেটিংস"),
        ["Language"] = ("Language / ভাষা", "ভাষা / Language"),
        ["ExpectedIncome"] = ("Expected monthly income", "সম্ভাব্য মাসিক আয়"),
        ["ExpectedIncomeHint"] = ("Used for the forecast and the \"need to borrow\" warning only in months without a monthly salary (above).", "উপরের মাসিক বেতন যে মাসে নেই, শুধু সেই মাসের পূর্বাভাস ও \"ধার লাগবে\" সতর্কতায় ব্যবহৃত হয়।"),
        ["Backup"] = ("Backup", "ব্যাকআপ"),
        ["BackupHint"] = ("All data lives only on this phone. Export a backup file and save it to Google Drive, so a lost phone doesn't mean lost data.", "সব তথ্য শুধু এই ফোনে থাকে। ব্যাকআপ ফাইল এক্সপোর্ট করে Google Drive-এ রাখুন, যাতে ফোন হারালেও তথ্য না হারায়।"),
        ["ExportBackup"] = ("Export backup", "ব্যাকআপ এক্সপোর্ট"),
        ["RestoreBackup"] = ("Restore from file", "ফাইল থেকে রিস্টোর"),
        ["LastBackup"] = ("Last backup: {0}", "শেষ ব্যাকআপ: {0}"),
        ["NeverBackedUp"] = ("Never backed up", "কখনও ব্যাকআপ হয়নি"),
        ["Restore_Confirm"] = ("Replace ALL current data with this backup from {0}?", "বর্তমান সব তথ্য মুছে {0} তারিখের ব্যাকআপ বসাবেন?"),
        ["Restore_Done"] = ("Backup restored.", "ব্যাকআপ রিস্টোর হয়েছে।"),
        ["Saved"] = ("Saved.", "সেভ হয়েছে।"),

        // ----- v2: Budget (ADR 0011) -----
        ["Tab_Budget"] = ("Budget", "বাজেট"),
        ["Budget_Title"] = ("Budget", "বাজেট"),
        ["Budget_Estimate"] = ("Estimate", "আনুমানিক"),
        ["Budget_Spent"] = ("Spent", "খরচ"),
        ["Budget_Left"] = ("Left", "বাকি"),
        ["Budget_Income"] = ("Income", "আয়"),
        ["Budget_IncomeExpected"] = ("Income (expected)", "আয় (সম্ভাব্য)"),
        ["Budget_IncomeParts"] = ("income {0} + borrowed {1}", "আয় {0} + ধার {1}"),
        ["Budget_Planned"] = ("Total planned", "মোট পরিকল্পনা"),
        ["Budget_TotalLeft"] = ("Left to pay / spend", "পরিশোধ / খরচ বাকি"),
        ["Budget_Save"] = ("Save", "সঞ্চয়"),
        ["Budget_NeedBorrow"] = ("You planned more than your income: need to borrow {0}", "আয়ের চেয়ে বেশি পরিকল্পনা: {0} ধার লাগবে"),
        ["Budget_Ok"] = ("Within income: {0} left to save", "আয়ের মধ্যে: {0} সঞ্চয় থাকবে"),
        ["Budget_Dues"] = ("Payments due this month", "এ মাসের পরিশোধ"),
        ["Budget_Items"] = ("Spending plan", "খরচের পরিকল্পনা"),
        ["Budget_NotInBudget"] = ("not in budget", "বাজেটে নেই"),
        ["Budget_OnCard"] = ("+ {0} on card, paid next month", "+ কার্ডে {0}, আগামী মাসে পরিশোধ"),
        ["Budget_AddItem"] = ("+ Add budget item", "+ বাজেট আইটেম যোগ"),
        ["Budget_Empty"] = ("No budget yet. Add items like Rent, Bajar, DPS. Next month copies them automatically.", "এখনও বাজেট নেই। ভাড়া, বাজার, ডিপিএস যোগ করুন। পরের মাসে নিজে থেকে কপি হবে।"),
        ["Budget_EstimateFor"] = ("Monthly estimate for {0}", "{0}-এর মাসিক আনুমানিক খরচ"),
        ["Budget_ChangeEstimate"] = ("Change estimate", "আনুমানিক বদলান"),
        ["Budget_Remove"] = ("Remove from budget", "বাজেট থেকে সরান"),
        ["Budget_ChooseCategory"] = ("Add which item?", "কোন আইটেম যোগ করবেন?"),
        ["Budget_NewCategory"] = ("+ New category…", "+ নতুন ক্যাটাগরি…"),
        ["Budget_TapToEdit"] = ("Tap an item to change the amount, stop it from next month, or delete it.", "পরিমাণ বদলাতে, আগামী মাস থেকে বন্ধ করতে বা মুছতে আইটেমে চাপুন।"),
        ["Budget_DueButton"] = ("Due ›", "বাকি ›"),
        ["Budget_ItemsTotal"] = ("Budget items", "বাজেট আইটেম"),
        ["Budget_EveryMonth"] = ("Monthly (comes every month)", "মাসিক (প্রতি মাসে থাকবে)"),
        ["Budget_OnlyThisMonth"] = ("Stop after this month", "এ মাসের পরে বন্ধ"),
        ["Budget_RepeatQuestion"] = ("Is {0} a monthly budget?", "{0} কি মাসিক বাজেট?"),
        ["Budget_TagEvery"] = ("Monthly", "মাসিক"),
        ["Budget_TagOnce"] = ("Stops after this month", "এ মাসের পরে বন্ধ"),
        ["Budget_MakeEvery"] = ("Make monthly again", "আবার মাসিক করুন"),
        ["Budget_MakeOnce"] = ("Stop from next month", "আগামী মাস থেকে বন্ধ করুন"),
        ["Budget_RemoveFuture"] = ("Delete from budget", "বাজেট থেকে মুছুন"),
        ["Budget_ConfirmDelete"] = ("Delete {0} from the budget? It won't come in the coming months either. Past months stay as they were.", "{0} বাজেট থেকে মুছবেন? পরের মাসগুলোতেও আর আসবে না। আগের মাস যেমন ছিল থাকবে।"),
        ["Home_PrevTitle"] = ("{0} summary", "{0} সারসংক্ষেপ"),
        ["Home_PrevSaved"] = ("Saved", "সঞ্চয়"),
        ["Home_PrevSub"] = ("income {0} − spent {1} − bills paid {2}", "আয় {0} − খরচ {1} − বিল পরিশোধ {2}"),
        ["Dues_DueIn"] = ("Due in {0}", "{0}-এ বাকি"),
        ["Settings_StartMonth"] = ("My data starts from", "আমার হিসাব শুরু"),
        ["Settings_StartSet"] = ("Starts from {0}", "{0} থেকে শুরু"),
        ["Settings_StartHint"] = ("Choose the first month you enter data for. Account opening balances are the balances on the 1st of that month, and every month from then on gets the Monthly budget.", "যে মাস থেকে হিসাব লিখবেন সেটি বেছে নিন। অ্যাকাউন্টের শুরুর ব্যালেন্স হবে ওই মাসের ১ তারিখের ব্যালেন্স, আর তখন থেকে প্রতি মাসে মাসিক বাজেট থাকবে।"),
        ["OpeningOn"] = ("Balance on {0}", "{0} তারিখের ব্যালেন্স"),
        ["Home_Budget"] = ("Budget this month", "এ মাসের বাজেট"),
        ["Home_BudgetSub"] = ("spent {0} · left {1}", "খরচ {0} · বাকি {1}"),

        // ----- v2: Home -----
        ["Dash_PlanSave"] = ("Save this month (plan)", "এ মাসের সঞ্চয় (পরিকল্পনা)"),
        ["Dash_PlanFormula"] = ("Income {0} − planned {1}", "আয় {0} − পরিকল্পনা {1}"),
        ["Dash_Planned"] = ("Planned", "পরিকল্পনা"),
        ["Dash_Spent"] = ("Paid + spent", "পরিশোধ + খরচ"),
        ["Dash_Left"] = ("Left", "বাকি"),
        ["Dash_OpenBudget"] = ("Budget", "বাজেট"),

        // ----- v3: Home (ADR 0018) -----
        ["Home_Savings"] = ("Savings this month", "এ মাসের সঞ্চয়"),
        ["Home_SavingsSub"] = ("left after all planned payments and spending", "সব পরিকল্পিত পরিশোধ ও খরচের পরে থাকবে"),
        ["Home_Expenses"] = ("Total expenses", "মোট খরচ"),
        ["Home_Due"] = ("Due", "দেনা"),
        ["Home_DuePending"] = ("{0} pending · next: {1} on {2}", "{0}টি বাকি · পরবর্তী: {1}, {2}"),
        ["Home_DueAllPaid"] = ("✓ All paid this month", "✓ এ মাসের সব পরিশোধিত"),
        ["Home_DueBudget"] = ("{0} budget items not paid yet", "{0}টি বাজেট আইটেম এখনও বাকি"),
        ["Home_DueLoans"] = ("loans {0}", "লোন {0}"),
        ["Home_DueNone"] = ("Nothing due", "কোনো দেনা নেই"),
        ["Home_CardPayment"] = ("Credit card payment", "ক্রেডিট কার্ড পরিশোধ"),
        ["Home_CardPending"] = ("Pending · due {0}", "বাকি · শেষ তারিখ {0}"),
        ["Home_CardPartial"] = ("Partly paid {0} · due {1}", "আংশিক {0} পরিশোধিত · শেষ তারিখ {1}"),
        ["Home_CardOverdue"] = ("Overdue since {0}", "{0} থেকে বকেয়া"),
        ["Home_CardNoBill"] = ("No bill this month", "এ মাসে বিল নেই"),
        ["Home_Accounts"] = ("Bank Balance", "ব্যাংক ব্যালেন্স"),
        // ----- Home of any month (ADR 0028) -----
        ["Home_AccountsOn"] = ("Bank Balance on {0}", "{0} তারিখে ব্যাংক ব্যালেন্স"),
        ["Home_SavingsIn"] = ("Savings in {0}", "{0}-এর সঞ্চয়"),
        ["Home_BudgetIn"] = ("Budget in {0}", "{0}-এর বাজেট"),
        ["Home_PrevCardIn"] = ("→ on {0}'s card bill", "→ {0}-এর কার্ড বিলে"),
        ["Home_PrevCarriedIn"] = ("→ unpaid, carried to {0}", "→ বাকি, {0}-এ এসেছে"),
        ["Home_ChooseMonth"] = ("Choose a month", "মাস বেছে নিন"),
        // ----- One month for all pages (ADR 0029) -----
        ["Acc_Balance"] = ("Balance now", "এখনকার ব্যালেন্স"),
        ["Acc_MonthSummary"] = ("On {0}: {1} · in {2} · out {3}", "{0}: {1} · জমা {2} · খরচ {3}"),
        ["Loan_PaidIn"] = ("{1} installment {0} · paid", "{1}-এর কিস্তি {0} · পরিশোধিত"),
        // ----- Month view of loans, pay month for borrowing (ADR 0030) -----
        ["Loan_InstallmentPaid"] = ("Installment {0} of {1} · {2} · paid", "{1}টির মধ্যে {0} নম্বর কিস্তি · {2} · পরিশোধিত"),
        ["Loan_InstallmentDue"] = ("Installment {0} of {1} · {2} · due {3}", "{1}টির মধ্যে {0} নম্বর কিস্তি · {2} · শেষ তারিখ {3}"),
        ["Debt_PayIn"] = ("pay in {0}", "{0}-এ ফেরত"),
        ["Debt_NoPayMonth"] = ("Not decided yet", "এখনও ঠিক হয়নি"),
        ["Debt_ChangeMonth"] = ("Change month", "মাস বদলান"),
        ["Debt_ChooseMonth"] = ("Pay back in which month?", "কোন মাসে ফেরত দেবেন?"),
        ["Debt_PayBackIn"] = ("Pay back in (month)", "ফেরত দেবেন (মাস)"),
        ["Debt_PayBackHint"] = ("From that month it is part of the month's dues, with a Pay button. You can change the month later.", "সেই মাস থেকে এটি মাসের দেনায় যোগ হবে, পরিশোধ বোতামসহ। পরে মাস বদলাতে পারবেন।"),
        ["Home_BackToThisMonth"] = ("Back to this month", "এ মাসে ফিরুন"),
        ["Home_PastMonthNote"] = ("You are looking at an earlier month.", "আপনি আগের একটি মাস দেখছেন।"),
        ["Home_NextMonth"] = ("{0} forecast", "{0} পূর্বাভাস"),
        ["Home_NextSub"] = ("after budget {0}, from income {1}", "বাজেট {0} বাদে, আয় {1} থেকে"),
        ["Home_AssumedSavings"] = ("Assumed savings", "সম্ভাব্য সঞ্চয়"),

        // ----- v2: Next-month forecast from the budget (ADR 0015) -----
        ["Fc_Payments"] = ("Card & loan payments", "কার্ড ও লোন পরিশোধ"),
        ["Fc_Budget"] = ("Budget", "বাজেট"),
        ["Fc_BudgetCopied"] = ("Budget (same as this month)", "বাজেট (এ মাসের মতো)"),
        ["Fc_Income"] = ("Expected income", "সম্ভাব্য আয়"),
        ["Fc_IncomeThisMonth"] = ("Income (same as this month)", "আয় (এ মাসের মতো)"),
        ["Fc_IncomeHint"] = ("Set your expected monthly income in Settings if it changes.", "আয় বদলালে সেটিংসে সম্ভাব্য মাসিক আয় দিন।"),

        // ----- v2: Card EMI & card bill (ADR 0012) -----
        ["Due_CardPayment"] = ("{0} payment", "{0} পরিশোধ"),
        ["Due_CardBreakdown"] = ("EMI {0} + purchases {1}", "ইএমআই {0} + কেনাকাটা {1}"),
        ["Card_ThisMonth"] = ("This month's payment", "এ মাসের পরিশোধ"),
        ["Card_PayBill"] = ("Pay card bill", "কার্ড বিল পরিশোধ"),
        ["Card_Emis"] = ("EMIs on this card", "এই কার্ডের ইএমআই"),
        ["Card_BillPurchases"] = ("Purchases on this bill", "এই বিলের কেনাকাটা"),
        ["Card_BillPurchasesSummary"] = ("{0} purchases · {1}", "{0}টি কেনাকাটা · {1}"),
        ["Card_BillPurchasesSummary1"] = ("{0} purchase · {1}", "{0}টি কেনাকাটা · {1}"),
        ["Card_OnBill"] = ("on {0} bill", "{0} মাসের বিলে"),
        ["Liab_LastMonth"] = ("Last month", "গত মাস"),
        // ----- This month tab, next month so far, won't pay (ADR 0031) -----
        ["Liab_ThisMonth"] = ("This month", "এ মাস"),
        // ----- Monthly card purchases, added by themselves (ADR 0038) -----
        ["Sub_Section"] = ("Monthly card payments", "মাসিক কার্ড পেমেন্ট"),
        ["Sub_Add"] = ("+ Add", "+ যোগ"),
        ["Sub_Hint"] = ("Added once, then charged to the card by itself every month on that day (e.g. an AI subscription). It goes on next month's card bill.", "একবার যোগ করলেই প্রতি মাসে ওই দিনে নিজে থেকে কার্ডে কাটা হবে (যেমন এআই সাবস্ক্রিপশন)। পরের মাসের কার্ড বিলে যাবে।"),
        ["Sub_Line"] = ("Day {0} every month · {1} · since {2}", "প্রতি মাসের {0} তারিখ · {1} · {2} থেকে"),
        ["Sub_StoppedFrom"] = ("stopped from {0}", "{0} থেকে বন্ধ"),
        ["Sub_Change"] = ("Change amount", "অঙ্ক বদলান"),
        ["Sub_AskName"] = ("Name (e.g. AI Subscription)", "নাম (যেমন এআই সাবস্ক্রিপশন)"),
        ["Sub_AskAmount"] = ("Amount every month for {0}", "{0}-এর প্রতি মাসের অঙ্ক"),
        ["Sub_AskDay"] = ("On which day of the month?", "মাসের কোন তারিখে?"),
        ["Sub_AskFrom"] = ("From which month?", "কোন মাস থেকে?"),
        ["Sub_AskNewAmount"] = ("New amount for {0} (from the next charge on)", "{0}-এর নতুন অঙ্ক (পরের বার থেকে)"),
        ["Sub_AskStop"] = ("Stop {0} from which month?", "{0} কোন মাস থেকে বন্ধ?"),
        // ----- Monthly salary (ADR 0035) -----
        ["Salary_Title"] = ("Monthly salary", "মাসিক বেতন"),
        ["Salary_Hint"] = ("Added automatically as income on the pay day of every month — no need to enter it. After an increment, set the new amount from that month; earlier months keep the old one.", "প্রতি মাসের বেতনের দিনে নিজে থেকেই আয় হিসেবে যোগ হবে — লিখতে হবে না। বেতন বাড়লে যে মাস থেকে বেড়েছে সেই মাস থেকে নতুন অঙ্ক দিন; আগের মাসগুলো আগের মতোই থাকবে।"),
        ["Salary_Amount"] = ("Amount", "অঙ্ক"),
        ["Salary_Day"] = ("Pay day", "বেতনের দিন"),
        ["Salary_Account"] = ("Paid into", "যে অ্যাকাউন্টে আসে"),
        ["Salary_From"] = ("From month", "যে মাস থেকে"),
        ["Salary_Save"] = ("Save salary", "বেতন সংরক্ষণ"),
        ["Salary_Stop"] = ("Stop", "বন্ধ"),
        ["Salary_Rate"] = ("From {0}: {1} on day {2} into {3}", "{0} থেকে: {2} তারিখে {1}, {3}-এ"),
        ["Salary_Stopped"] = ("From {0}: stopped", "{0} থেকে: বন্ধ"),
        ["Salary_Saved"] = ("Salary {0} from {1} saved. It is added automatically every month.", "{1} থেকে বেতন {0} সংরক্ষিত। প্রতি মাসে নিজে থেকেই যোগ হবে।"),
        ["Salary_ConfirmStop"] = ("Stop the salary from {0}? Earlier months keep theirs.", "{0} থেকে বেতন বন্ধ করবেন? আগের মাসগুলো থাকবে।"),
        ["Err_Day"] = ("The pay day must be between 1 and 31.", "বেতনের দিন ১ থেকে ৩১-এর মধ্যে হতে হবে।"),
        // ----- Cash flow details (ADR 0032) -----
        ["Flow_MoneyIn"] = ("Money in", "আয় ও জমা"),
        ["Flow_InHint"] = ("Everything that came into your accounts this month: income, money borrowed and money returned to you.", "এ মাসে অ্যাকাউন্টে যা এসেছে: আয়, ধার নেওয়া টাকা এবং ফেরত পাওয়া টাকা।"),
        ["Flow_DuesHint"] = ("Card bills, loan installments and repayments paid this month. Tap a card bill to see its purchases.", "এ মাসে পরিশোধ করা কার্ড বিল, লোনের কিস্তি ও ধার ফেরত। কার্ড বিলে চাপলে কেনাকাটাগুলো দেখা যাবে।"),
        ["Flow_BillHint"] = ("The purchases on this card bill, paid in {0}: {1} of {2}.", "এই কার্ড বিলের কেনাকাটা, {0}-এ পরিশোধ: {2}-এর মধ্যে {1}।"),
        ["Flow_SpentHint"] = ("Paid in cash or from the bank this month, by category. Tap one to see its items.", "এ মাসে নগদ বা ব্যাংক থেকে খরচ, ক্যাটাগরি অনুযায়ী। আইটেম দেখতে চাপুন।"),
        ["Flow_BorrowedFrom"] = ("Borrowed from {0}", "{0}-এর কাছ থেকে ধার"),
        ["Flow_BorrowedNote"] = ("to pay back · see Liabilities → Personal", "ফেরত দিতে হবে · দায় → ব্যক্তিগত দেখুন"),
        ["Flow_ReturnedBy"] = ("Returned by {0}", "{0} ফেরত দিয়েছেন"),
        ["Flow_Entries"] = ("{0} entries", "{0}টি এন্ট্রি"),
        ["Flow_Entry1"] = ("1 entry", "১টি এন্ট্রি"),
        ["Flow_Installment"] = ("{0} · installment {1} of {2}", "{0} · {2}টির মধ্যে {1} নম্বর কিস্তি"),
        ["Flow_CardPurchases"] = ("{0} · {1} purchases", "{0} · {1}-এর কেনাকাটা"),
        ["Flow_Repaid"] = ("Paid back {0}", "{0}-কে ফেরত"),
        ["Flow_From"] = ("from {0}", "{0} থেকে"),
        ["Flow_PartOf"] = ("part of {0}", "{0}-এর অংশ"),
        ["Liab_ThisMonthHint"] = ("Card purchases of this month's cycle. They are paid with next month's card bill.", "এ মাসের চক্রের কার্ডের কেনাকাটা। এগুলো পরের মাসের কার্ড বিলে পরিশোধ হবে।"),
        ["Card_NextMonthIn"] = ("Next month so far · {0}", "পরের মাস এখন পর্যন্ত · {0}"),
        ["Card_NextEmi"] = ("EMI", "ইএমআই"),
        ["Card_NextPurchases"] = ("Purchases", "কেনাকাটা"),
        ["Card_NextTotal"] = ("Total", "মোট"),
        ["Budget_Skip"] = ("Won't pay this month (strike through)", "এ মাসে দেব না (কেটে দিন)"),
        ["Budget_Unskip"] = ("Will pay after all (remove strike)", "দেব (কাটা তুলে নিন)"),
        ["Budget_Skipped"] = ("Not paying this month · planned {0}", "এ মাসে দেওয়া হচ্ছে না · পরিকল্পনা {0}"),
        ["Dues_Skip"] = ("Skip", "বাদ দিন"),
        ["Dues_Unskip"] = ("Undo", "ফিরিয়ে আনুন"),
        ["Dues_SkippedTitle"] = ("Not paying this month", "এ মাসে দেওয়া হচ্ছে না"),
        ["Liab_LastMonthHint"] = ("Card purchases of last month. They are paid with this month's card bill.", "গত মাসের কার্ডের কেনাকাটা। এগুলো এ মাসের কার্ড বিলে পরিশোধ হয়।"),
        ["Card_PaidNote"] = ("{0} paid on {1}", "{1} তারিখে {0} পরিশোধিত"),
        ["Card_LimitUsed"] = ("Limit used {0} of {1}", "লিমিট ব্যবহৃত {1}-এর {0}"),
        ["Card_Paid"] = ("Paid", "পরিশোধিত"),
        ["Edit"] = ("Edit", "এডিট"),
        ["EditAccount_Title"] = ("Edit account", "অ্যাকাউন্ট এডিট"),
        ["EditCard_Title"] = ("Edit card", "কার্ড এডিট"),
        ["LoanCard"] = ("Billed on credit card (EMI)", "ক্রেডিট কার্ডে বিল (ইএমআই)"),
        ["PaidBefore"] = ("Installments already paid", "আগে পরিশোধিত কিস্তি"),
        ["NextInstallment"] = ("Next installment to pay", "পরবর্তী কিস্তির তারিখ"),
        ["Loan_OnCard"] = ("EMI on {0}", "{0}-এ ইএমআই"),
        // ----- Loans with / without installments, money received (ADR 0034) -----
        ["LoanKind_Emi"] = ("With installments (EMI)", "কিস্তিতে (ইএমআই)"),
        ["LoanKind_One"] = ("Without installments", "কিস্তি ছাড়া"),
        ["LoanKind_OneHint"] = ("One amount, paid with the card bill of the month you choose. You can change the month or convert it into EMI later.", "এক কিস্তিতে, যে মাস বাছবেন সেই মাসের কার্ড বিলে দেবেন। পরে মাস বদলাতে বা ইএমআই করতে পারবেন।"),
        ["LoanPayMonth"] = ("Pay in (month)", "পরিশোধের মাস"),
        ["LoanMoneyReceived"] = ("Money received now", "টাকা এখন পেয়েছি"),
        ["LoanMoneyReceivedHint"] = ("It goes into the account and counts in that month's income as borrowed. Turn off for a loan that was already running.", "টাকাটা অ্যাকাউন্টে যাবে এবং সেই মাসের আয়ে ধার হিসেবে গোনা হবে। আগে থেকে চলা লোনের জন্য বন্ধ রাখুন।"),
        ["LoanReceivedIn"] = ("Received in", "যেখানে পেয়েছি"),
        ["Loan_SubOne"] = ("{0} · one amount, no installments", "{0} · এক কিস্তিতে, কিস্তি ছাড়া"),
        ["Loan_OneDue"] = ("Pay in {0}", "{0}-এ দিতে হবে"),
        ["Loan_OnePaid"] = ("Paid in {0}", "{0}-এ পরিশোধিত"),
        ["Loan_StartsIn"] = ("Starts {0} · {1} a month · pending", "{0} থেকে শুরু · মাসে {1} · বাকি"),
        ["Loan_Convert"] = ("Convert to EMI", "ইএমআই করুন"),
        ["Loan_ConvertTotal"] = ("Total to pay in installments (unpaid {0}; add the bank's interest if any)", "কিস্তিতে মোট কত দেবেন (বাকি {0}; ব্যাংকের সুদ থাকলে যোগ করুন)"),
        ["Loan_ConvertCount"] = ("How many installments?", "কয়টি কিস্তি?"),
        ["Loan_ConvertFrom"] = ("First installment in which month?", "প্রথম কিস্তি কোন মাসে?"),
        ["Loan_ChoosePayMonth"] = ("Pay in which month?", "কোন মাসে দেবেন?"),
        ["Loan_ChooseStartMonth"] = ("Unpaid installments start in which month?", "বাকি কিস্তি কোন মাস থেকে শুরু?"),
        ["Err_LoanNothingOpen"] = ("Nothing of this loan is left to move or convert.", "এই লোনের সরানো বা বদলানোর মতো কিছু বাকি নেই।"),
        ["Err_AlreadyEmi"] = ("This loan is already in installments.", "এই লোন আগেই কিস্তিতে আছে।"),
        ["Flow_LoanFrom"] = ("Loan: {0}", "লোন: {0}"),
        ["Flow_LoanNote"] = ("to pay back · see Liabilities → Loans", "ফেরত দিতে হবে · দায় → লোন দেখুন"),

        // ----- v2: Items & categories (ADR 0013) -----
        ["Items"] = ("Items", "আইটেম"),
        ["AddItemLine"] = ("+ Add item", "+ আইটেম যোগ"),
        ["UseItems"] = ("Enter item by item (Rice 5kg 450…)", "আইটেম ধরে লিখুন (চাল ৫কেজি ৪৫০…)"),
        ["ItemName"] = ("Item", "আইটেম"),
        ["Qty"] = ("Qty", "পরিমাণ"),
        // ----- Qty × rate, units, no duplicate categories (ADR 0027) -----
        ["Item_Rate"] = ("Rate", "দর"),
        ["Item_RatePer"] = ("Rate/{0}", "দর/{0}"),
        ["Item_Calc"] = ("{0} × {1} = {2}", "{0} × {1} = {2}"),
        ["Item_QtyPrice"] = ("{0} · {1}", "{0} · {1}"),
        ["Item_OptionalHint"] = ("Only item and price are needed. Add qty and rate to calculate the price.", "শুধু আইটেম আর দাম দিলেই হবে। পরিমাণ আর দর দিলে দাম নিজেই হিসাব হবে।"),
        ["Unit_kg"] = ("kg", "কেজি"),
        ["Unit_gm"] = ("gm", "গ্রাম"),
        ["Unit_ltr"] = ("ltr", "লিটার"),
        ["Unit_ml"] = ("ml", "মিলি"),
        ["Unit_pcs"] = ("pcs", "পিস"),
        ["Unit_dozen"] = ("dozen", "ডজন"),
        ["Unit_packet"] = ("packet", "প্যাকেট"),
        ["Category_ExistsSelected"] = ("\"{0}\" already exists, so it is selected.", "\"{0}\" আগেই আছে, তাই সেটাই বেছে নেওয়া হলো।"),
        ["Category_ExistsUnder"] = ("\"{0}\" already exists under {1}.", "\"{0}\" আগেই {1}-এর নিচে আছে।"),
        ["Category_ExistsTop"] = ("\"{0}\" already exists as a category.", "\"{0}\" নামে ক্যাটাগরি আগেই আছে।"),
        ["Budget_AlreadyInPlan"] = ("\"{0}\" is already in this month's spending plan.", "\"{0}\" এ মাসের খরচের পরিকল্পনায় আগেই আছে।"),
        ["Price"] = ("Price", "দাম"),
        ["SubCategory"] = ("Type", "ধরন"),
        ["ItemsTotal"] = ("Total {0}", "মোট {0}"),
        ["Categories_Title"] = ("Categories", "ক্যাটাগরি"),
        ["ManageCategories"] = ("Categories", "ক্যাটাগরি"),
        ["ManageCategoriesHint"] = ("Add people (Parents, Children…) or sub-categories (Bajar → Fish). Tap a category to rename or delete it.", "ব্যক্তি (মা-বাবা, সন্তান…) বা উপ-ক্যাটাগরি (বাজার → মাছ) যোগ করুন। নাম বদলাতে বা মুছতে ক্যাটাগরিতে চাপুন।"),
        ["AddCategory"] = ("+ Add category", "+ ক্যাটাগরি যোগ"),
        ["NewCategoryButton"] = ("+ New", "+ নতুন"),
        ["Confirm_DeleteCategory"] = ("Delete \"{0}\"? It is also removed from every month's budget.", "\"{0}\" মুছে ফেলবেন? সব মাসের বাজেট থেকেও সরে যাবে।"),
        ["Confirm_DeleteSub"] = ("Delete \"{0}\"? Its entries move to {1}.", "\"{0}\" মুছে ফেলবেন? এর এন্ট্রিগুলো {1}-এ চলে যাবে।"),
        ["Err_CategoryInUse"] = ("This category already has entries, so it can't be deleted. You can rename it instead.", "এই ক্যাটাগরিতে এন্ট্রি আছে, তাই মোছা যাবে না। চাইলে নাম বদলাতে পারেন।"),
        ["Err_LastCategory"] = ("You need at least one category of this kind.", "এই ধরনের অন্তত একটি ক্যাটাগরি থাকতে হবে।"),
        ["AddSub"] = ("+ Sub", "+ উপ"),
        ["NewCategory_Prompt"] = ("Name of the new category", "নতুন ক্যাটাগরির নাম"),
        ["NewSub_Prompt"] = ("New sub-category under {0}", "{0}-এর নতুন উপ-ক্যাটাগরি"),
        ["Rename"] = ("Rename", "নাম বদলান"),
        ["Rename_Prompt"] = ("New name", "নতুন নাম"),
        ["ExpenseCategories"] = ("Expense categories", "খরচের ক্যাটাগরি"),
        ["IncomeCategories"] = ("Income categories", "আয়ের ক্যাটাগরি"),
        ["Reports_TopItems"] = ("Top items this month", "এ মাসে বেশি খরচের আইটেম"),
        ["NoItems"] = ("No items recorded this month.", "এ মাসে কোনো আইটেম নেই।"),
        ["Reports_TapHint"] = ("Tap a category to see its groups and items.", "গ্রুপ ও আইটেম দেখতে ক্যাটাগরিতে চাপুন।"),
        ["CatReport_Groups"] = ("By group", "গ্রুপ অনুযায়ী"),
        ["CatReport_Budget"] = ("Budget {0} · spent {1} · left {2}", "বাজেট {0} · খরচ {1} · বাকি {2}"),
        ["CatReport_CashCard"] = ("cash {0} · card {1}", "নগদ {0} · কার্ড {1}"),
        ["CatReport_Empty"] = ("Nothing spent in this category this month.", "এ মাসে এই ক্যাটাগরিতে কোনো খরচ নেই।"),
        ["CatReport_OnCard"] = ("card", "কার্ড"),

        // ----- Errors (keys thrown by Core as FinanceException) -----
        ["Err_PaidBefore"] = ("Already-paid installments must be fewer than the total.", "আগে পরিশোধিত কিস্তি মোট কিস্তির চেয়ে কম হতে হবে।"),
        ["Err_SubOfSub"] = ("A sub-category can't have its own sub-category.", "উপ-ক্যাটাগরির আবার উপ-ক্যাটাগরি হয় না।"),
        ["Err_CategoryExists"] = ("A category or sub-category with this name already exists.", "এই নামে ক্যাটাগরি বা উপ-ক্যাটাগরি আগেই আছে।"),
        ["Err_BudgetCategory"] = ("Budget items must be main expense categories.", "বাজেট শুধু মূল খরচের ক্যাটাগরিতে।"),
        ["Err_Amount"] = ("Enter an amount greater than zero.", "শূন্যের বেশি পরিমাণ লিখুন।"),
        ["Err_Account"] = ("Choose an account.", "একটি অ্যাকাউন্ট বেছে নিন।"),
        ["Err_SameAccount"] = ("From and To must be different accounts.", "দুটি ভিন্ন অ্যাকাউন্ট বেছে নিন।"),
        ["Err_Card"] = ("Choose a card.", "একটি কার্ড বেছে নিন।"),
        ["Err_Type"] = ("This type can't be added here.", "এই ধরন এখানে যোগ করা যাবে না।"),
        ["Err_NotFound"] = ("Record not found.", "রেকর্ড পাওয়া যায়নি।"),
        ["Err_CardBilled"] = ("This purchase's card bill is already paid, so it can't be deleted.", "এই কেনাকাটার কার্ড বিল পরিশোধ হয়ে গেছে, তাই মোছা যাবে না।"),
        ["Err_DeleteDebtTx"] = ("Borrow/lend records are managed under Liabilities.", "ধার নেওয়া/দেওয়া দায় অংশ থেকে পরিচালনা করুন।"),
        ["Err_Name"] = ("Enter a name.", "একটি নাম লিখুন।"),
        ["Err_Installments"] = ("Enter the number of monthly installments (1–600).", "মাসিক কিস্তির সংখ্যা লিখুন (১–৬০০)।"),
        ["Err_LoanHasPayments"] = ("This loan already has payments, so it can't be deleted.", "এই লোনে পরিশোধ হয়েছে, তাই মোছা যাবে না।"),
        ["Err_Day"] = ("Enter a valid day of month.", "মাসের সঠিক দিন লিখুন।"),
        ["Err_TooMuch"] = ("That's more than what's left to pay.", "বাকির চেয়ে বেশি দেওয়া যাবে না।"),
        ["Err_BackupInvalid"] = ("This is not a valid Daily Account backup file.", "এটি সঠিক ব্যাকআপ ফাইল নয়।"),
        ["Err_BackupNewer"] = ("This backup was made by a newer version of the app. Update the app first.", "এই ব্যাকআপ নতুন ভার্সনের। আগে অ্যাপ আপডেট করুন।"),
        // Example hints (placeholders): always "e.g. …" so they don't look like a typed value.
        ["Ph_LoanName"] = ("e.g. Loan-1", "যেমন: লোন-১"),
        ["Ph_LoanTotal"] = ("e.g. 50000", "যেমন: ৫০০০০"),
        ["Ph_Installments"] = ("e.g. 6", "যেমন: ৬"),
        ["Ph_CardName"] = ("e.g. Visa", "যেমন: ভিসা"),
        ["Ph_Limit"] = ("e.g. 320000", "যেমন: ৩২০০০০"),
        ["Ph_Income"] = ("e.g. 100000", "যেমন: ১০০০০০"),
        ["Err_Unexpected"] = ("Something went wrong: {0}", "সমস্যা হয়েছে: {0}"),
    };
}
